# Generated by Django 2.2 on 2019-04-21 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meettitle', models.CharField(max_length=255)),
                ('meetdate', models.DateField()),
                ('meettime', models.TimeField()),
                ('meetlocation', models.CharField(max_length=255)),
                ('meetagenda', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'meetings',
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcename', models.CharField(max_length=255)),
                ('resourcetype', models.TextField(blank=True, null=True)),
                ('resourceURL', models.URLField(blank=True, null=True)),
                ('resourcedateentered', models.DateField()),
                ('resourcedescription', models.TextField(blank=True, null=True)),
                ('resourceuserid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutetext', models.TextField(blank=True, null=True)),
                ('minuteattendance', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('minuteid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pythonapp.Meeting')),
            ],
            options={
                'verbose_name_plural': 'minutes',
                'db_table': 'minutes',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=255)),
                ('eventlocation', models.CharField(max_length=255)),
                ('eventdate', models.DateField()),
                ('eventdescription', models.TextField(blank=True, null=True)),
                ('eventuserid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'events',
                'db_table': 'event',
            },
        ),
    ]
